Drive straigt
hackbots-3414/2022-Rapid_React pull request #20
Opened 2022-01-25 00:48 UTC by bczdog

2022-01-29 19:04 UTC, sanjana36 requested changes
please update DriveStraight spelling

2022-01-29 19:04 UTC, sanjana36 commented on 2022-RapidReact/src/main/java/frc/robot/commands/DriveStraigt.java
> +public class DriveStraigt extends CommandBase {
Please update the spelling of DriveStraight

2022-01-31 23:29 UTC, AdriaanFriesen commented
Fixed name, reopening

2022-02-05 16:27 UTC, bczdog commented
Fixes confirmed

2022-02-12 14:52 UTC, closed without merging

2022-02-12 14:52 UTC, bczdog commented
No longer required.